### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/funny-lemur#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, you'll be added as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by mohitgarg** [comment]
Add as a collaborator!

**Comment by nmessier86** [comment]
Add as a collaborator.

**Comment by ireeve** [comment]
Add as a collaborator!

**Comment by AnnMajeske** [comment]
Add as a collaborator

**Comment by edoardomarsili** [comment]
Hi :-)

**Comment by calebbontrager** [comment]
Add as collaborater...

**Comment by kr-abhishek-cse** [comment]
Please add me as a collaborator!

**Comment by michaelschmit** [comment]
Add as a collaborator.

**Comment by wca2000** [comment]
add me please

**Comment by lcardani** [comment]
Here is my comment!

Larry

**Comment by razor5900** [comment]
Add me please

**Comment by groberge** [comment]
Add as a collaborator.

**Comment by daveharder-dell** [comment]
Good morning!

**Comment by shubhamdhama** [comment]
Add as a collaborator

**Comment by shashankaalse** [comment]
Add asa collaborator

**Comment by neuwib** [comment]
Add me please.

**Comment by andrericardo** [comment]
Please add me as collaborator :)

**Comment by maxrupp** [comment]
Add as a collaborator

**Comment by codeShar** [comment]
Please add me!

**Comment by lawlopez3** [comment]
Screen image scale way too small.

**Comment by mschibilla** [comment]
Please add me :-)

**Comment by GregVVach** [comment]
Add as a collaborator...

**Comment by akiemr19** [comment]
This is my first issue.

**Comment by myersb-dell** [comment]
Add as a collaborator.

**Comment by kmolnar2** [comment]
me too

**Comment by sfsofia** [comment]
Add me please.

**Comment by lily08** [comment]
add me please

**Comment by jgboyd** [comment]
Please add me as a collaborator

**Comment by lawlopez3** [comment]
Add as a collaborator

**Comment by chandreshsharma** [comment]
My first GitHub comment

**Comment by RamuKMLG** [comment]
Please add me as collaborator!!

**Comment by ArtiShelar** [comment]
Please add me as a collaborator.

**Comment by nikhilbhambure** [comment]
Please add me as collaborator

**Comment by githubteacher** [comment]
:tada: @mohitgarg, @nmessier86, @ireeve, @AnnMajeske, @edoardomarsili, @calebbontrager, @kr-abhishek-cse, @michaelschmit, @wca2000, @lcardani, @razor5900, @groberge, @daveharder-dell, @shubhamdhama, @shashankaalse, @neuwib, @andrericardo, @maxrupp, @codeShar, @lawlopez3, @mschibilla, @GregVVach, @akiemr19, @myersb-dell, @kmolnar2, @sfsofia, @lily08, @jgboyd, @lawlopez3, @chandreshsharma, @RamuKMLG, @ArtiShelar, and @nikhilbhambure are now  repository collaborators. :balloon:

**Comment by moganamourthy** [comment]
1st comment

**Comment by dunbam01** [comment]
Here's a comment.

**Comment by yhe1971** [comment]
add me as a collaborator please

**Comment by githubteacher** [comment]
:tada: @moganamourthy, @dunbam01, and @yhe1971 are now  repository collaborators. :balloon:

**Comment by yasirjanjua** [comment]
add as collaborator

**Comment by lucifiel0121** [comment]
first Add as a comment!

**Comment by githubteacher** [comment]
:tada: @yasirjanjua and @lucifiel0121 are now  repository collaborators. :balloon:

**Comment by zhaican** [comment]
add me

**Comment by jashasweejena** [comment]
Add me as a collaborator please :)

**Comment by JinkyungLim** [comment]
I want to be added as a collaborator

**Comment by crichID** [comment]
@githubteacher I think you should totally watch this issue!

**Comment by lcardani** [comment]
I am not getting emails but am subscribed by default.

**Comment by githubteacher** [comment]
:tada: @zhaican, @jashasweejena, and @JinkyungLim are now  repository collaborators. :balloon:

**Comment by midatana** [comment]
Add me as collaborator

**Comment by githubteacher** [comment]
:tada: @midatana is now a repository collaborator. :balloon:

**Comment by skapelos** [comment]
Add me

**Comment by brentd-smith** [comment]
i'm here, running late

**Comment by githubteacher** [comment]
:tada: @skapelos and @brentd-smith are now  repository collaborators. :balloon:

**Comment by kbtoyz123** [comment]
I just found the project - please add me

**Comment by githubteacher** [comment]
:tada: @kbtoyz123 is now a repository collaborator. :balloon:

**Comment by perrej1** [comment]
I just signed in. Please add me.

**Comment by githubteacher** [comment]
:tada: @perrej1 is now a repository collaborator. :balloon:

**Comment by zenjen777** [comment]
just saw where to comment. :)

**Comment by pratapvedula** [comment]
signed in now , please add me.

**Comment by amuodd** [comment]
please add me as a collaborator

**Comment by githubteacher** [comment]
:tada: @zenjen777, @pratapvedula, and @amuodd are now  repository collaborators. :balloon:

**Comment by orakwue** [comment]
pls add need to be added as a collaborator

**Comment by Jonathanliu92251** [comment]
please Add as a collaborator!

**Comment by Jonathanliu92251** [comment]
add me please
