### ISSUE TITLE
Some help ##help wanted

### ISSUE THREAD

**Issue by sfsofia** [githubschool/funny-lemur#130]
On the next set of commands:
$ git commit -m "add categories to sfsofia hometown file"
$ git push
$ git remote set-url origin .....
what I must add at the last one?

**Comment by githubteacher** [comment]
@sfsofia `git remote -u origin your-branch` followed by a `git push`

**Comment by crichID** [comment]
@sfsofia yes, the correct command would be `git remote set-url origin https://github.com/githubschool/funny-lemur.git` You can grab this clone URL from the Code Tab of the repository.
