### ISSUE TITLE
How to assign issue to pull request ?

### ISSUE THREAD

**Issue by lawlopez3** [githubschool/funny-lemur#132]
@beardofedu

**Comment by githubteacher** [comment]
@lawlopez3 in the text of your Pull Request, add `closes #issuenumber` if you start to type `#lawlopez3` it will find your issue if you created your issue with your user name.

**Comment by crichID** [comment]
@lawlopez3 if you want more options, check out this help doc: https://help.github.com/articles/closing-issues-via-commit-messages/
