### ISSUE TITLE
How to get to editor?

### ISSUE THREAD

**Issue by lcardani** [githubschool/funny-lemur#135]
@beardofedu How do I get from my PR to the editor?  Where is the pencil icon?

**Comment by githubteacher** [comment]
@lcardani 
In your Pull Request, select the Files Changed tab, then click on the pencil on the right hand side. 

![screen shot 2017-04-17 at 10 17 40 am](https://cloud.githubusercontent.com/assets/2132216/25091438/17568a22-2357-11e7-9773-ab80c3153e8b.png)

**Comment by lcardani** [comment]
Found it, thanks.
