### ISSUE TITLE
The commands history #help wanted

### ISSUE THREAD

**Issue by sfsofia** [githubschool/funny-lemur#141]
Please share the  commands history  for today

**Comment by githubteacher** [comment]
@sfsofia Where are you in the project, so I can provide the command history you need. Also, all of the commands and activities that we have gone through today (and tomorrow) can be found in the GitHub for Developers manual which can be found here: https://github.github.io/training-manual/

There is also a Cheat Sheet for common Git commands, found here: https://services.github.com/resources/cheatsheets/

If you need more information, please let me know.
