### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by lawlopez3** [githubschool/funny-lemur#142]
@beardofedu 
@crichID 

a crib sheet that people could refer to would help.
this would help a lot.

You can probably generate one on a running basis by looking at the issues.

I expect you are already doing this.

since the screen you are present is unreadable some portion of the time you have to remember @cri 
to send a message.

Mostly the issue reporting scheme helps.

**Comment by githubteacher** [comment]
@lawlopez3 All of the commands and activities that we have gone through today (and tomorrow) can be found in the GitHub for Developers manual which can be found here: https://github.github.io/training-manual/

There is also a Cheat Sheet for common Git commands, found here: https://services.github.com/resources/cheatsheets/

If you need more information, please let me know.
