### ISSUE TITLE
Reload the config file

### ISSUE THREAD

**Issue by jgboyd** [githubschool/funny-lemur#147]
Is there a way to reload the config file without exiting Git Bash Shell?

**Comment by githubteacher** [comment]
@jgboyd What do you mean by reload?

**Comment by jgboyd** [comment]
After setting a config file option using "git config" I have to exit the bash shell and restart it to get the new config setting to take affect.  Is there a way to get it to take affect without exiting and restarting the bash shell. This is a windows system

**Comment by crichID** [comment]
@jgboyd this is interesting and something I have not heard before. The git configs are set in a separate file from the .bashrc or .bash_profile, so I wouldn't think restarting the bash shell would have any effect. Hopefully you are setting git configs infrequently and this will be less noticeable in the future.
