### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by edoardomarsili** [githubschool/funny-lemur#149]
Do you hold or translate the classes in other languages?

**Comment by crichID** [comment]
@edoardomarsili we do not offer the class in anything other than English at this time. We do have git cheat sheets available in several languages if it would be helpful: https://services.github.com/resources/cheatsheets/

**Comment by edoardomarsili** [comment]
@crichID, could it be something you can pass through your staff as a feature?

**Comment by crichID** [comment]
> could it be something you can pass through your staff as a feature?

@edoardomarsili we are looking at working with partners who can deliver in other languages, but we are still a few months away from anything official. I promise it is on our list though :+1:. Is there a specific language(s) you are looking for?

**Comment by edoardomarsili** [comment]
@crichID not me in specific, but wondering for Italian as an example. If you would like to keep me informed and need a channel for future reference please send an acknowledgement email to edoardomarsili@outlook.com.

**Comment by crichID** [comment]
@edoardomarsili thank you! I have jotted down your information and will reach out when we have more info!
