### ISSUE TITLE
Video is lagging too much

### ISSUE THREAD

**Issue by kr-abhishek-cse** [githubschool/funny-lemur#158]

**Comment by crichID** [comment]
@kr-abhishek-cse I am not seeing any lag on my end, is it possible to reset your connection and see if it improves?

**Comment by kr-abhishek-cse** [comment]
stucked at verifying the meeting id

**Comment by crichID** [comment]
@kr-abhishek-cse 😦 is it working now?

**Comment by kr-abhishek-cse** [comment]
@crichID Now its working
