### ISSUE TITLE
Thanks for the sessions!

### ISSUE THREAD

**Issue by lcardani** [githubschool/funny-lemur#167]
@crichID @beardofedu 
Thanks to both of you for your sessions.  Good job being flexible when Matt's internet failed.

In the future, you might want to consider having all (or at least the most useful!) of the commands documented in one place (if possible), so we don't have to take notes furiously and get behind (which I did!).

Also, the Chat was disabled.  I think that would have been a quicker way to send you comments / feedback . issues.  It took a bit longer, using Issues.  And one person could feed the other person some useful questions/comments, improving the class in real time.

Great job, I learned a ton!

Larry C.

**Comment by crichID** [comment]
Hi @lcardani thank you for your feedback. We appreciate you taking the time to drop us a note and give great advice. We agree that the chat interface leaves a lot to be desired, but we will be switching to a new tool very soon with a much better chat experience.

One quick follow up note, you can find all of the commands (along with some of the explanations) in the training manual [linked in the README](https://github.github.io/training-manual/).
