### ISSUE TITLE
Yasir's things to do

### ISSUE THREAD

**Issue by yasirjanjua** [githubschool/funny-lemur#45]
- [x] Make issues
- [ ] Make branches
- [ ] Make repos
- [ ] Make commits
- [ ] Merge

**Comment by crichID** [comment]
@yasirjanjua this is really close - just make sure you enter the list syntax as `- [ ] ` (with spaces) to get the cool checklist in your comment.

**Comment by yasirjanjua** [comment]
![img](https://octodex.github.com/images/catstello.png)
