### ISSUE TITLE
Should the chat window be working?

### ISSUE THREAD

**Issue by groberge** [githubschool/funny-lemur#48]
I don't seem to be able to ask questions in chat.  Is this normal?

**Comment by crichID** [comment]
@groberge for some reason GTW chat doesn't let students ask questions. I am happy to answer any of your questions here though!

**Comment by groberge** [comment]
Thank you.  I don't have anything at the moment but I wanted to know what's available.

**Comment by dunbam01** [comment]
So the user name we entered in the shell is a different user name than our github account user name?
@crich

**Comment by crichID** [comment]
> So the user name we entered in the shell is a different user name than our github account user name?

@dunbam01 in the shell you are typically using the name people call you when they see you in the hall :wink: Git is going to bake that information in every time you create a commit, so people will see who made the commit.

**Comment by dunbam01** [comment]
Thank you.  I thought so, but was afraid to use a different name for fear that it wouldn’t work!
