### ISSUE TITLE
Cannot create a chat issue

### ISSUE THREAD

**Issue by lcardani** [githubschool/funny-lemur#49]
I don't see how to create a chat issue

**Comment by lcardani** [comment]
I see the Questions / Chat dropdown  and some existing entries, but don't see how to create a question via chat.

**Comment by crichID** [comment]
@lcardani are you referring to chat in GoToWebinar? Let's do questions here instead because issues are a much better interface for asking and answering questions.

**Comment by lcardani** [comment]
OK, thanks.
