### ISSUE TITLE
Backup/Restore github settings?

### ISSUE THREAD

**Issue by razor5900** [githubschool/funny-lemur#50]
Is there a way to save current settings and later restore as a set without having to re-issue individual setting changes?

**Comment by crichID** [comment]
@razor5900 this is something you could script Git to do for you. The only settings you won't want to keep from today are probably the username and email if you are using a different account for class. If that is the case, you can also just set these local to the repository we are using after we clone it.

**Comment by razor5900** [comment]
I have multiple github repositories i access.  two separate ones internal to my company in addition to (now) this public one.  would be nice to simply fire a script that reconfigures accordingly...  was looking for a built in git feature to manage such

**Comment by razor5900** [comment]
@crichID ,  where should I research git scripting... of course I can/will google, but if you have a pointer that would be great.

Thanks!

**Comment by crichID** [comment]
@razor5900 there are some general examples here: https://github.com/github/training-utils

They might be a good place to start. Basically, I do it all with Bash. So you could do something like this:

```
#!/bin/sh

git config --local user.name "My Name"
git config --local user.email "my@email.com"
```

Then change permissions on that file to allow it to execute commands (e.g. `chmod 766 FILENAME`) and run `bash FILENAME`.

**Comment by razor5900** [comment]
Thanks.  I've written boat loads of bash.

Seems funny (-lemur) to me that a version control system doesn't have features to version control itself...
