### ISSUE TITLE
I can't clone my repo...

### ISSUE THREAD

**Issue by GregVVach** [githubschool/funny-lemur#61]
@crichID 

Hi I can't clone it

"Permission denied"

**Comment by githubteacher** [comment]
@GregVVach Try to use the SSH link from the `Clone or Download` drop down. Clicking the `Use SSH` option will populate the field with the SSH link.

**Comment by GregVVach** [comment]
@crichID 

Something doesn't work...

I can't do "git init" command also...

"Permission denied" is the answer....

**Comment by githubteacher** [comment]
@GregVVach Are you on a work computer with limited access rights?

**Comment by GregVVach** [comment]
It is my computer...

**Comment by githubteacher** [comment]
@GregVVach so, if you create a directory and type `git init` you get an error? Can you paste your error text in the issue?

**Comment by GregVVach** [comment]
![error](https://cloud.githubusercontent.com/assets/20682946/25090583/5a9cf3ac-2384-11e7-8dea-104a64ca14a7.png)

That's all...

**Comment by GregVVach** [comment]
![error2](https://cloud.githubusercontent.com/assets/20682946/25090614/8d45b398-2384-11e7-9c94-402ec6ee23b8.png)

**Comment by githubteacher** [comment]
@GregVVach run your Terminal application as an Administrator and let me know if you still run into an issue. If you need help getting caught up, let me know.

**Comment by GregVVach** [comment]
I did it as Administrator...

So now I have repo of my branch on my computer, but I'm pretty lost in lesson...

**Comment by githubteacher** [comment]
@GregVVach Ok, I can get you caught up:

1. Checkout your branch using `git checkout your-branch-name`
2. Create a new file using `touch username-city.md` ; if `touch` doesn't work, you can create the file inside File Explorer within your repository. 
3. Add content to your file (places to visit or eat within your city)
4. On the command line, run `git status` to see that Git identifies your file but isn't tracking it
5. Enter `git add file-name` on your command line
6. Enter `git status` to see that your file is ready to be committed
7. Enter `git commit` on your command line
8. Enter a commit message (you might be in vi) and then press the following: Esc key, `:wq` Enter key.
9. After you create a commit, enter `git push` on your command line.
10. Create a Pull Request

**Comment by GregVVach** [comment]
Hi again,
I'm not sure, I did right way with git clone command (I think I get master branch with all members files), and now I  have  a problem with git push screenshot below:

![error3](https://cloud.githubusercontent.com/assets/20682946/25092882/f43a103e-238f-11e7-98d1-7f6abfe12809.png)

**Comment by crichID** [comment]
@GregVVach ok - it looks like there are a couple fun things happening here.

- you created the branch gregvvach-lublin on your local machine, but it looks like you created a new one (probably using `git branch gregvvach-lublin` before you typed `git checkout gregvvach-lublin`. The `git branch` command basically created a new branch and ignored the one from github. That's why it was confused when you pushed the first time and asked you to do the `--set-upstream`
- However, since you had created a branch with the same name on github, the second error is telling you that you need to merge the two together before you can push. 

## To Fix it

- You should be able to type `git pull` to merge the remote branch into your local one.
- After that you should be able to do `git push`.

If that doesn't work, let me know and we can troubleshoot some more!

**Comment by GregVVach** [comment]
@crichID 

Hi, I can do **git pull**, but I still can't do 'git push'

![github7](https://cloud.githubusercontent.com/assets/20682946/25106008/91e61058-23c7-11e7-9933-c32041d46e82.png)

**Comment by crichID** [comment]
Hi @GregVVach let's try a little wizardry here:

- Run `git fetch`
- Then type `git merge --allow-unrelated --no-edit`
- Then type `git push -u origin gregvvach-lublin`

**Comment by GregVVach** [comment]
`git merge --allow-unrelated --no-edit` didn;t work...

![github8](https://cloud.githubusercontent.com/assets/20682946/25107231/60c1c286-23ce-11e7-8f3c-068ed8cfaa6a.png)

**Comment by crichID** [comment]
@GregVVach sorry, that was my bad instructions. You will need to be explicit about the branch you want to merge since there is no remote tracking relationship set. `git merge --allow-unrelated origin/gregvvach-lublin`

**Comment by GregVVach** [comment]
@crichID printscreen that I put below, after combo inputs I suppose have to do :)

1. `git fetch`
2. `git merge --allow-unrelated origin/gregvvach-lublin`
3. `git push -u origin gregvvach-lublin`


![github10](https://cloud.githubusercontent.com/assets/20682946/25121536/50f0c9d4-2422-11e7-867b-b77bd3604434.png)

What are next steps I need to do before another lesson?

**Comment by crichID** [comment]
@GregVVach you probably already know this, but we are starting with a new repository today! If you want to finish out the steps in the repository from yesterday, you can find the instructions here: https://github.github.io/training-manual/#_git_push

**Comment by GregVVach** [comment]
@crichID  Yes, I'm learning today right now.

Thanks a lot for instructions link. I'll try to finish it. :1st_place_medal:
