### ISSUE TITLE
What is the *.md extension for?

### ISSUE THREAD

**Issue by lcardani** [githubschool/funny-lemur#75]
@crichID

**Comment by githubteacher** [comment]
@lcardani the *.md extension creates a `markdown` file. Markdown is just a file format that GitHub can stylize. Fun fact, Issues and Pull Requests use Markdown to be able to use:

- lists

# Headings

**bold**

_italics_

**Comment by mohitgarg** [comment]
@lcardani You can learn more about the markdown [here](https://guides.github.com/features/mastering-markdown/)
