### ISSUE TITLE
Please share the previous steps before you set the new BRANCH

### ISSUE THREAD

**Issue by sfsofia** [githubschool/funny-lemur#76]

**Comment by githubteacher** [comment]
@sfsofia Matt here, can you provide some context to your question, so I can give a solid answer?

**Comment by sfsofia** [comment]
On gitshell there where executed some commands, before the teachear set the current brach.
What where those commands, this happend on the moment the connection problems started

**Comment by githubteacher** [comment]
So, I ran:

- `git clone https://github.com/githubschool/funny-lemur.git`
- I `cd`-ed into the repo using `cd funny-lemur`
- Check your branch out using  `git checkout your-branch-name`
